const SITE_URL = "https://motionstory.com.au";

/** First-party poster. Regenerated by scripts/fetch-vimeo-posters.mjs */
export function vimeoPosterUrl(vimeoId: string): string {
  return `/posters/${vimeoId}.jpg`;
}

export function vimeoPosterAbsoluteUrl(vimeoId: string): string {
  return `${SITE_URL}${vimeoPosterUrl(vimeoId)}`;
}
